# Generated by Django 5.1.6 on 2025-06-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='start_date',
            new_name='rental_date',
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Truck', 'Truck'), ('Electric', 'Electric'), ('Sedan', 'Sedan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/cars_img/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
